#define Size size
#define Capacity capacity
#define Data data
#define Front front
#define Back back
#define CStr cstring
#define Empty empty
#define Length length
#define Clear clear
#define Swap swap
#define PopBack pop_back
#define PushBack push_back
#define Resize resize
#define Reserve reserve
#define ShrinkToFit shrink